name: Team Murray
favicon: null
layout_spectrum: 0.894442044198513
typography_spectrum: 0.015111182117834687
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c2827'
    - '#1f0000'
    - '#e2b016'
    - '#c67815'
    - '#bd3833'
  brandStrength: 0.6108997275587171
  lightness: 0.27189176762476563
  saturation: 0.18436476518400013
  rhythmicContrast: 0.025913667399436235
purpose: []
