name: Team Murray
favicon: null
layout_spectrum: 0.894442044198513
typography_spectrum: 0.015111182117834687
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c2827'
    - '#1f0000'
    - '#e2b016'
    - '#c67815'
    - '#bd3833'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
